// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdrouyzulkemmgrqicpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkcm91eXp1bGtlbW1ncnFpY3BxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MDQ0OTgsImV4cCI6MjA2MzA4MDQ5OH0.VUwON3W1gO17Gx7liFtVbUBrNe9FARxzxzQdXxU1jnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);